### ISSUE TITLE
docs make bails out on CTRL-C

### ISSUE THREAD

**Issue by thaJeztah** [docker/docs-base#2]
Just noticed that whenever I <kbd>CTRL</kbd>+<kbd>C</kbd> the docs-make container I get some errors;

```bash

[SNIP]
docker run --rm -it  -e AWS_S3_BUCKET -e NOCACHE -p 8000:8000 "docker-docs:11069-run-reference-restart-policies" mkdocs serve
Running at: http://0.0.0.0:8000/
Live reload enabled.
Hold ctrl+c to quit.

[SNIP]

[03/Mar/2015 23:16:33] "GET /versions.html_fragment HTTP/1.1" 200 -
^CTraceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 4, in <module>
    __import__('pkg_resources').run_script('mkdocs==0.9', 'mkdocs')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs-0.9-py2.7.egg/EGG-INFO/scripts/mkdocs", line 46, in <module>
    main(cmd, args=sys.argv[2:], options=dict(opts))
  File "/usr/local/lib/python2.7/dist-packages/mkdocs-0.9-py2.7.egg/EGG-INFO/scripts/mkdocs", line 29, in main
    serve(config, options=options)
  File "/usr/local/lib/python2.7/dist-packages/mkdocs-0.9-py2.7.egg/mkdocs/serve.py", line 109, in serve
    server.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
KeyboardInterrupt
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/watchdog-0.7.0-py2.7.egg/watchdog/observers/api.py", line 242, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
make: *** [docs] Error 1

```

Nothing serious (since you want the container to stop anyway).

Running `docker (client)` on my OS X 10.10.2, connected to a remote docker daemon via a SSH tunnel. Can give more info if needed.

**Comment by SvenDowideit** [comment]
yup, mkdocs isn't handling the `exit hard left` ctrl-c and so treats it as a request to dump stack - pretty standard python.

**Comment by thaJeztah** [comment]
Ah, alright. Should this be added to the docs README, so that people are not surprised that this happens? Or is there a way to suppress it/fix it.

Feel free to close if there's nothing actionable for *this* repo (or leave it open as tracker) :smile:

**Comment by moxiegirl** [comment]
Closing for now. I think a graceful shutdown is a nice-to-have at this point.  We'll be adjusting the build in the future so let's revisit in a couple of months.

**Comment by thaJeztah** [comment]
sgtm
